// Case-owned definition and interaction copy.
export const definition = Object.freeze({
    id: "creator",
    kicker: "Creator App · AI Editing",
    title: "Viva Video",
    summary: "成熟出海 C 端创作工具里的 AI 玩法包装、入口设计、创作完成和反馈闭环。",
    status: "VivaVideo / VivaCut 商店页、AI 玩法与数字人工作流。",
    visual: "creator",
    headerImage: "assets/headers/viva-header-pixel.png",
    headerAlt: "像素风 Viva Video AI 创作编辑工作台",
    pages: [
      {
        type: "viva-intro",
        label: "Project Intro",
        title: "成熟创作工具里的 AI 玩法落地",
        summary: "在 C 端视频创作工具里，把 AI 能力包装成用户能理解、愿意尝试、能导出分享的创作路径。",
        footprints: [
          { title: "VivaVideo", src: "assets/vivavideo/商店页截图/vivavideo.jpg", alt: "VivaVideo App Store 页面截图" },
          { title: "VivaCut", src: "assets/vivavideo/商店页截图/vivacut.jpg", alt: "VivaCut App Store 页面截图" },
        ],
        tags: ["AI 玩法", "编辑体验", "首页触达", "内容供给", "数据反馈"],
      },
      {
        type: "viva-shelf",
        label: "AI Play Shelf",
        title: "把模型能力变成可尝试的玩法货架",
        summary: "把图像、视频、音乐、数字人、字幕和视觉编辑组织成可直接尝试、并能回到编辑链路的 AI 创作入口。",
        plays: [
          {
            title: "AI Magic Templates",
            icon: "✦",
            kind: "Template discovery",
            src: "assets/vivavideo/ai-magic-templates-ui-reconstruction-v2.png",
            alt: "AI Magic Templates phone UI reconstruction based on the original product flow",
            want: "用户想快速找到灵感。",
            wrap: "用 Hot 分类和模板网格包装 AI 能力。",
            next: "点开模板后进入生成或编辑。",
          },
          {
            title: "AI Video Creation",
            icon: "▶",
            kind: "Video creation",
            src: "assets/vivavideo/ai-video-creation-ui-reconstruction-v2.png",
            alt: "AI Video Creation phone UI reconstruction based on the original product flow",
            want: "用户有想法但没有完整视频素材。",
            wrap: "用 prompt、图片和 AI Writing 降低输入门槛。",
            next: "点击 Generate 生成可继续剪辑的视频。",
          },
          {
            title: "AI Music",
            icon: "♫",
            kind: "Sound generation",
            src: "assets/vivavideo/ai-music-ui-reconstruction-v2.png",
            alt: "AI Music phone UI reconstruction based on the original product flow",
            want: "用户需要适配视频氛围的音乐。",
            wrap: "用描述、风格和 credits 形成可理解的消费路径。",
            next: "生成后进入配乐和导出链路。",
          },
          {
            title: "Digital Human",
            icon: "◉",
            kind: "Presenter creation",
            src: "assets/vivavideo/digital-human-ui-reconstruction-v2.png",
            alt: "Digital Human phone UI reconstruction based on the original product flow",
            want: "用户想用虚拟人做讲解或内容表达。",
            wrap: "用形象、声音和文本组合驱动视频。",
            next: "生成后继续编辑字幕、画面和声音。",
          },
          {
            title: "Auto Caption",
            icon: "CC",
            kind: "Caption editing",
            src: "assets/vivavideo/auto-caption-ui-reconstruction-v2.png",
            alt: "Auto Caption phone UI reconstruction based on the original product flow",
            want: "用户需要更快完成字幕包装。",
            wrap: "识别文字后接入样式面板和编辑工具。",
            next: "确认样式后进入剪辑完成链路。",
          },
          {
            title: "Text Brush",
            icon: "↗",
            kind: "Canvas lettering",
            src: "assets/vivavideo/text-brush-ui-reconstruction-v2.png",
            alt: "Text Brush phone UI reconstruction based on the original product flow",
            want: "用户想让文字成为画面的一部分。",
            wrap: "用路径文字和画布编辑承接视觉创作。",
            next: "完成后导出或进入二次编辑。",
          },
        ],
      },
      {
        type: "viva-loop",
        label: "Digital Human",
        title: "把数字人做成可复用的创作资产",
        summary: "通过一条可操作工作流，展示角色、动作、声音、口型和编辑草稿如何逐层组合成口播视频。",
        steps: [
          {
            id: "character",
            label: "Character",
            title: "创建数字人",
            short: "上传照片，生成可复用角色",
            layer: "角色资产",
            input: "一张正面照片",
            output: "可复用角色卡",
            artSrc: "assets/vivavideo/digital-human-character-ui-v1.png",
            artAlt: "数字人角色资产创建界面",
            copy: "先把角色从一次性素材变成可持续使用的创作资产。",
            note: "后续换动作、脚本和音色时，不必重新创建角色。",
          },
          {
            id: "motion",
            label: "Motion",
            title: "生成动作循环",
            short: "为同一角色准备不同动态",
            layer: "动作资产",
            input: "角色形象卡",
            output: "可替换动作循环",
            artSrc: "assets/vivavideo/digital-human-motion-ui-v1.png",
            artAlt: "数字人动作循环资产界面",
            copy: "动作被单独抽出来，角色可以在不同口播场景里继续复用。",
            note: "身体动作先成为可选资产，后面再与声音和口型组合。",
          },
          {
            id: "script",
            label: "Script & Voice",
            title: "输入脚本与音色",
            short: "决定说什么，以及怎么说",
            layer: "声音内容层",
            input: "脚本文案 + 音色",
            output: "音频时间轴",
            artSrc: "assets/vivavideo/digital-human-script-voice-ui-v1.png",
            artAlt: "数字人脚本与音色配置界面",
            copy: "脚本和音色先形成独立的声音层，不把内容锁死在角色生成里。",
            note: "用户改一句话或换一个音色，不必重做角色和动作。",
          },
          {
            id: "sync",
            label: "Lip-sync",
            title: "口型驱动预览",
            short: "先确认声音和表情是否同步",
            layer: "面部表现层",
            input: "音频时间轴 + 角色",
            output: "口型预览",
            artSrc: "assets/vivavideo/digital-human-lipsync-ui-v1.png",
            artAlt: "数字人口型同步预览界面",
            copy: "让声音时间点驱动面部表现，动作循环继续承担身体运动。",
            note: "把问题发现前置到最终合成之前，避免直接等待一条不合适的成片。",
          },
          {
            id: "compose",
            label: "Compose",
            title: "合成可编辑草稿",
            short: "把各层放回视频编辑链路",
            layer: "合成与编辑层",
            input: "角色 + 动作 + 音频 + 口型",
            output: "可编辑口播草稿",
            artSrc: "assets/vivavideo/digital-human-compose-ui-v1.png",
            artAlt: "数字人可编辑口播草稿时间线界面",
            copy: "最终视频不是黑盒终稿，而是还可以调整字幕、背景和节奏的草稿。",
            note: "数字人能力回到 Viva Video 的主创作链路，Export 只是其中一个终点。",
          },
        ],
        motions: [
          { label: "Talk", detail: "稳定口播" },
          { label: "Nod", detail: "点头回应" },
          { label: "Gesture", detail: "手势强调" },
        ],
        voices: [
          { label: "Warm", detail: "温和" },
          { label: "Clear", detail: "清晰" },
          { label: "Bright", detail: "明亮" },
        ],
        defaultScript: "今天用一个角色，把想法说给更多人听。",
      },
      {
        type: "viva-learning",
        label: "Workflow Logic",
        title: "数字人工作流背后的四个产品判断",
        summary: "四个产品判断覆盖资产复用、模块解耦、渲染预览与生成后编辑。",
        learnings: [
          {
            title: "角色资产与内容分离",
            short: "一个角色，多条内容",
            question: "如果角色和每次口播绑定，换一句脚本就要从头开始。",
            design: "先创建可复用角色，再让脚本、音色和动作成为后续内容层。",
            benefit: "一次角色创建可以服务多条口播内容，减少重复操作。",
            how: "把角色形象视为独立资产，后续步骤只引用角色，不重新创建。",
            signal: "角色创建完成率 / 同一角色再次使用率",
          },
          {
            title: "动作与口型解耦",
            short: "身体和表达各自可替换",
            question: "身体动作和口型绑在一起时，换脚本或换动作都要整段重做。",
            design: "动作循环作为身体层，音频时间轴和口型作为面部表达层，最后组合。",
            benefit: "动作、脚本和音色可以独立修改，复用空间更大。",
            how: "维护 Motion Loop、Audio Track、Lip-sync Preview 三个可替换状态。",
            signal: "动作替换后的重做比例 / 单个角色产生的内容版本数",
          },
          {
            title: "渲染前提供预览",
            short: "先检查，再合成",
            question: "如果直到成片才发现口型不同步，用户会等待一次无效渲染。",
            design: "在最终合成前提供短时口型预览，让用户先检查表达。",
            benefit: "把错误发现前置，减少无效渲染，提升控制感。",
            how: "用 Preview 状态承接音频检查与口型确认，再进入最终合成。",
            signal: "预览到最终合成的转化率 / 预览阶段修改率",
          },
          {
            title: "结果保留编辑能力",
            short: "生成后仍然可以继续做",
            question: "数字人如果只能生成和下载，会脱离 Viva Video 的主编辑链路。",
            design: "合成结果进入可编辑时间线，保留角色、动作、音频和字幕层。",
            benefit: "用户可以继续调整内容，形成真正的创作完成感。",
            how: "Compose 状态保留图层和 Edit Again，导出只是一个结果出口。",
            signal: "进入编辑的比例 / 编辑后导出或分享比例",
          },
        ],
      },
    ],
  });

export const journeyByTitle = Object.freeze({
  "AI Magic Templates": {
    input: "从 Hot 模板入口挑一个视觉方向，输入门槛很低。",
    working: "玩法把模型能力包装成模板网格，让用户先选感觉，再决定要不要生成。",
    output: "得到一版可继续替换素材和调整节奏的模板结果。",
    edit: "换模板、改素材或直接导出分享。",
  },
  "AI Video Creation": {
    input: "用一句 prompt、几张图片或 AI Writing 交代视频想法。",
    working: "系统把文字意图、图片和生成选项组合成一个创作任务。",
    output: "生成一条可进入剪辑时间线继续处理的视频草稿。",
    edit: "继续剪辑、改字幕、换音乐或导出。",
  },
  "AI Music": {
    input: "描述视频氛围，选择风格和长度，确认一次生成消耗。",
    working: "把抽象的音乐能力转成可理解的描述、风格和试听决策。",
    output: "得到一段能放进视频时间线继续调整的配乐草稿。",
    edit: "试听、替换、微调或进入导出。",
  },
  "Digital Human": {
    input: "选择数字人形象、声音和要表达的文本。",
    working: "把人物、语音和文本组合为一条可预览的视频任务。",
    output: "得到带有画面、声音和字幕的讲解视频草稿。",
    edit: "替换人物、修正文本、改字幕或导出。",
  },
  "Auto Caption": {
    input: "把视频送入字幕入口，先确认识别结果和语言。",
    working: "识别文字后，把内容接到样式、位置和时间轴编辑。",
    output: "得到一条已经完成字幕包装的视频版本。",
    edit: "改词、调节奏、换样式或导出。",
  },
  "Text Brush": {
    input: "输入一句文字并选择它要沿着画面走的方向。",
    working: "把文字从普通字幕变成画布上的路径元素，保留视觉控制。",
    output: "得到一版可以继续编辑路径和样式的视觉文字。",
    edit: "拖动路径、调整字效或导出。",
  },
});
