// Case-owned definition and public artifact manifests.
export const definition = Object.freeze({
    id: "dokie",
    kicker: "Agent · Office",
    title: "Dokie",
    summary: "办公与演示智能体，把想法、文件或对话转成可编辑、可导出、可继续精修的办公内容。",
    status: "真实产品界面、多格式产物与 Agent 执行链路。",
    visual: "agent",
    headerImage: "assets/headers/dokie-header-pixel.png",
    headerAlt: "像素风 Dokie AI 办公智能体工作区",
    pages: [
      {
        type: "dokie-intro",
        label: "Project Intro",
        title: "把输入变成可交付办公内容",
        summary: "从输入到可编辑产物。",
        logo: "assets/dokie/logo-dokie.png",
        hero: {
          src: "assets/dokie/首页-public.png",
          alt: "Dokie 首页和新任务入口",
          note: "公开裁切的产品首页证据，突出新任务输入和快捷操作。",
        },
        tags: ["PPT", "Long Scroll", "Draft", "Visuals", "Editable Output"],
        role: "办公 Agent 的入口判断、工具编排、多格式输出和结果精修链路。",
      },
      {
        type: "dokie-workflow",
        label: "Workflow Map",
        title: "从一次生成到可迭代工作流",
        summary: "Dokie 先理解输入，再规划结构、生成格式、允许精修，最后用质量标准判断结果能否交付。",
        inputPacket: {
          title: "One brief, many deliverables",
          copy: "用户带着主题、文件、提示词或品牌要求进入任务，而不是从一段空泛聊天开始。",
          tags: ["Topic", "File", "Prompt", "Brand request"],
        },
        steps: [
          ["Plan", "识别任务类型、结构、输出格式和素材需求"],
          ["Build", "Slides / Long Scroll / Draft / Visuals"],
          ["Refine", "Change theme / Convert to / Edit / Export"],
          ["Learn", "用 Structure、Design、Editability、Export 反补判断"],
        ],
        outputs: [
          { title: "Slides", src: "assets/dokie/多格式产物showcase/PPT/001.png", alt: "Dokie PPT 真实产物" },
          { title: "Long Scroll", src: "assets/dokie/多格式产物showcase/长图.png", alt: "Dokie Long Scroll 真实产物" },
          { title: "Draft", src: "assets/dokie/多格式产物showcase/Draft文档.png", alt: "Dokie Draft 真实产物" },
        ],
        quality: [
          ["Structure", "信息层级清楚，内容有可读的起点。"],
          ["Design", "视觉服务内容，而不是只换一套模板。"],
          ["Editability", "生成后还能继续修改和转换。"],
          ["Export", "结果可以分享、导出和复用。"],
        ],
        execution: {
          task: "把一份产品发布需求整理成 8 页提案，并保持清晰的科技感视觉方向。",
          fields: [
            ["Format", "PPT"],
            ["Audience", "产品与增长团队"],
            ["Tone", "清爽蓝 / 视觉优先"],
            ["Delivery", "可编辑演示文稿"],
          ],
          parse: [
            ["Audience", "产品与增长团队"],
            ["Goal", "讲清产品发布故事"],
            ["Format", "8 页演示文稿"],
            ["Key info", "问题 → 方案 → 证据"],
            ["Visual tone", "清晰的科技感方向"],
          ],
          outline: [
            ["Cover", "发布承诺与核心观点"],
            ["Problem", "值得解决的阻力"],
            ["Solution", "用户会发生什么变化"],
            ["Key Features", "支撑观点的证据"],
            ["Use Cases", "产品适合在哪里发挥作用"],
            ["Market", "外部环境与关键信号"],
            ["Roadmap", "下一步怎么走"],
            ["CTA", "需要做出的下一项决策"],
          ],
          template: ["Tech pitch", "Clean blue", "Visual-first"],
          tools: [
            ["Brief Parser", "关键信息已提取"],
            ["Outline Builder", "故事主线已形成"],
            ["Template Matcher", "已选择蓝色视觉方向"],
            ["Slide Composer", "内容已映射到页面"],
            ["Visual Layout", "已应用层级与间距"],
            ["Quality Check", "已复核交付风险"],
          ],
          slides: [
            ["Cover", "发布故事与核心观点"],
            ["Problem", "值得解决的阻力"],
            ["Solution", "给用户更清晰的路径"],
            ["Key Features", "用证据代替功能堆叠"],
            ["Use Cases", "真正重要的使用时刻"],
            ["Market", "支撑决策的外部背景"],
            ["Roadmap", "持续精修的路径"],
            ["CTA", "准备进入下一步"],
          ],
          qualityLens: [
            ["Structure", "故事从问题推进到决策。"],
            ["Design", "视觉层级帮助信息被理解。"],
            ["Editability", "生成后仍然可以继续修改。"],
            ["Export", "结果已经可以分享和交付。"],
          ],
          refine: [
            ["Change theme", "尝试另一套视觉方向"],
            ["Edit outline", "调整故事主线"],
            ["Convert to Long Scroll", "复用同一份内容"],
            ["Export", "准备可编辑演示文稿"],
          ],
        },
      },
      {
        type: "dokie-formats",
        label: "Format Showcase",
        title: "多格式不是标签，是不同交付场景",
        summary: "同一段输入需要落到演示、长图或文档里，用户下一步要能继续编辑、分享或导出。",
        inputPacket: "同一份主题、文件、提示词和品牌要求",
        formats: [
          {
            title: "PPT",
            src: "assets/dokie/多格式产物showcase/PPT/001.png",
            alt: "Dokie PPT 真实产物",
            input: "主题、资料或结构输入",
            output: "可编辑演示文稿",
            next: "继续换主题、改字、导出或分享。",
          },
          {
            title: "Long Scroll",
            src: "assets/dokie/多格式产物showcase/长图.png",
            alt: "Dokie 长图真实产物",
            input: "适合传播的内容结构",
            output: "可阅读、可分享的长图",
            next: "面向社媒、汇报或复用场景继续精修。",
          },
          {
            title: "Draft",
            src: "assets/dokie/多格式产物showcase/Draft文档.png",
            alt: "Dokie 文档真实产物",
            input: "写作、提纲或文件素材",
            output: "结构化文档草稿",
            next: "继续编辑正文、补资料和组织结构。",
          },
        ],
      },
      {
        type: "dokie-template",
        label: "Template System / HTML Quality",
        title: "看一个模板如何被做出来",
        summary: "不展示模板海量，而是拆解大纲、页面角色、HTML 结构、CSS 变量和质量检查。",
        cases: [],
        quality: [
          ["结构", "先判断信息结构，再生成页面。"],
          ["设计", "让风格服务内容，而不是只换模板。"],
          ["可编辑性", "生成后还能改主题、文字和布局。"],
          ["导出", "结果要能交付、分享和复用。"],
        ],
      },
    ],
  });

export const artifactManifest = Object.freeze([
  {
    id: "ppt",
    title: "PPT",
    mode: "翻页查看",
    countLabel: "9 pages",
    description: "适合需要逐页讲述、继续编辑和导出的演示场景。",
    items: Array.from({ length: 9 }, (_, index) => ({
      src: `assets/dokie/多格式产物showcase/PPT/${String(index + 1).padStart(3, "0")}.png`,
      alt: `Dokie PPT 真实产物第 ${index + 1} 页`,
      label: `Page ${String(index + 1).padStart(2, "0")}`,
    })),
  },
  {
    id: "long-scroll",
    title: "Long Scroll",
    mode: "内部滚动",
    countLabel: "1 long canvas",
    description: "适合让同一条内容沿着阅读节奏展开，而不是被拆成页面。",
    items: [{ src: "assets/dokie/多格式产物showcase/长图.png", alt: "Dokie Long Scroll 真实产物", label: "Long canvas" }],
  },
  {
    id: "draft",
    title: "Draft",
    mode: "文档阅读",
    countLabel: "1 document",
    description: "适合从提纲进入正文，保留继续补资料和修改结构的空间。",
    items: [{ src: "assets/dokie/多格式产物showcase/Draft文档.png", alt: "Dokie Draft 真实产物", label: "Draft document" }],
  },
  {
    id: "social",
    title: "Image / Social Carousel",
    mode: "多图翻页",
    countLabel: "6 images",
    description: "适合把同一主题拆成一组可连续浏览、继续改图文的社媒内容。",
    items: Array.from({ length: 6 }, (_, index) => ({
      src: `assets/dokie/多格式产物showcase/社媒多图/Dokie_Product_Introduction_-_Image_Format_${String(index + 1).padStart(3, "0")}.png`,
      alt: `Dokie 社媒多图真实产物第 ${index + 1} 张`,
      label: `Image ${String(index + 1).padStart(2, "0")}`,
    })),
  },
]);

export const templateSystem = Object.freeze({
  stages: [
    ["Brief", "先把主题、受众、目标和交付格式整理成可执行输入。"],
    ["Outline", "把内容变成页面角色，而不是直接把文字塞进模板。"],
    ["Page roles", "明确每页承担的叙事任务：开场、问题、证据、下一步。"],
    ["Layout groups", "按内容密度选择布局组，保持结构和视觉节奏。"],
    ["Parallel page tasks", "把页面任务拆开并行推进，再回到同一套检查标准。"],
    ["HTML pages", "每页是可阅读、可检查的 HTML，而不是不可编辑的图片。"],
    ["Review", "检查结构、层级、溢出、一致性和交付可用性。"],
  ],
  roles: [
    ["01", "Cover", "一句话建立主题和视觉方向"],
    ["02", "Problem", "让读者知道为什么现在要看"],
    ["03", "Solution", "把变化讲成可理解路径"],
    ["04", "Proof", "用证据而不是功能堆叠支撑观点"],
    ["05", "Next step", "给出下一步决策或行动"],
  ],
  tasks: [
    ["Task 01", "Page 01–02", "建立入口与问题"],
    ["Task 02", "Page 03–05", "展开方案与证据"],
    ["Task 03", "Page 06–09", "收束路线与下一步"],
  ],
  tokens: [
    ["Color", "--color-ink / --color-accent", "同一套语义颜色贯穿页面"],
    ["Type", "--font-display / --font-body", "短标题与长文本各自可读"],
    ["Space", "--space-2 / --space-4 / --space-8", "用节奏而不是随机间距组织页面"],
    ["Safe area", "--safe-top / --safe-bottom", "让内容留在可交付的安全区"],
  ],
  checks: [
    ["Structure", "页面角色和阅读顺序清楚"],
    ["Hierarchy", "标题、正文、证据有层级"],
    ["Overflow", "没有被裁切或挤出安全区的内容"],
    ["Consistency", "token、布局和组件行为保持一致"],
    ["Editability", "输出仍然可以继续改和转格式"],
  ],
});
