// Case-owned definition. Keep SoundsNomad changes in this directory.
export const definition = Object.freeze({
  id: "indie",
  kicker: "Indie · SoundsNomad",
  title: "SoundsNomad",
  summary: "一个从音频内容底座延伸到 Field → Discovery Card → Echo Garden 的移动声音产品。",
  status: "基线产品用真实截图证明；Field 是网页内唯一可推进的本地交互演示。",
  visual: "indie",
  headerImage: "assets/headers/soundsnomad-header-pixel.png",
  headerAlt: "像素风 SoundsNomad 声音探索与 Echo Garden 场景",
  pages: [
    {
      type: "sounds-intro",
      label: "Project Intro",
      title: "把声音从内容库，延伸到真实场景。",
      summary: "SoundsNomad 以睡眠、专注与放松为核心，把可组合的声音内容延伸到 Field：用户在地点中发现声源，再将结果收进 Echo Garden。",
      badge: "01 / 04 · Product snapshot",
      evidence: {
        src: "cases/soundsnomad/assets/home-featured.png",
        alt: "真实 SoundsNomad Home 与 Featured Mixes 产品截图",
        label: "Home / Featured Mixes",
      },
      productProof: [
        ["01", "Sounds", "内容库"],
        ["02", "Player", "混音播放"],
        ["03", "Echo Garden", "场景收藏"],
      ],
      tags: ["Mobile audio", "Field discovery", "Echo Garden"],
      decision: "真实界面与可交互模块分工明确。",
      footnote: "Field 将地点线索接回声音内容。",
    },
    {
      type: "sounds-field",
      label: "Field Scan Flow",
      title: "从地图声源，到 Echo Garden。",
      summary: "交互原型链路：地图选点 → 扫描状态 → Discovery Card → Echo Garden。",
      badge: "02 / 04 · Live module",
      scanSteps: ["Capturing ambience", "Analyzing texture", "Shaping discovery"],
      evidence: {
        map: {
          src: "cases/soundsnomad/assets/field-map.png",
          alt: "真实 SoundsNomad Field 地图与本地声源卡片截图",
        },
        discovery: {
          src: "cases/soundsnomad/assets/discovery-card-detail.png",
          alt: "真实 SoundsNomad Discovery Card 卡片主体截图",
        },
        garden: {
          src: "cases/soundsnomad/assets/echo-garden-list.png",
          alt: "真实 SoundsNomad Echo Garden 列表截图",
        },
      },
      flow: ["FIND", "SCAN", "CARD", "KEEP"],
      sources: [
        {
          id: "street_tree",
          x: 21,
          y: 35,
          marker: "Maple Tree",
          clue: "A dry leaf rhythm hides under the walkway shadow.",
          object: "Maple Tree",
          sound: "Maple Leaves at Dusk",
          place: "Cupertino · Maple Walk",
          tags: ["leaf", "soft", "outside"],
          gardenSlot: "Window rain",
        },
        {
          id: "rain_bench",
          x: 64,
          y: 28,
          marker: "Rain Bench",
          clue: "A damp wooden bench tone sits under the after-rain air.",
          object: "Rain Bench",
          sound: "Rain Afterglow Bench",
          place: "Cupertino · North Garden Seat",
          tags: ["rain", "wood", "garden"],
          gardenSlot: "After-rain seat",
        },
        {
          id: "garden_stream",
          x: 48,
          y: 68,
          marker: "Pocket Stream",
          clue: "A hidden water thread is moving behind the fern pocket.",
          object: "Pocket Stream",
          sound: "Fern Pocket Stream",
          place: "Cupertino · Fern Pocket",
          tags: ["water", "tiny", "green"],
          gardenSlot: "Distant kettle",
        },
        {
          id: "fog_window",
          x: 78,
          y: 59,
          marker: "Fogged Window",
          clue: "A quiet window hum waits inside the glass lane.",
          object: "Fogged Window",
          sound: "Warm Window Drizzle",
          place: "Cupertino · Glass Lane",
          tags: ["window", "drizzle", "warm"],
          gardenSlot: "After-rain seat",
        },
      ],
      garden: {
        name: "Moon Window",
        base: 1,
        total: 3,
        slots: ["Window rain", "After-rain seat", "Distant kettle"],
      },
    },
    {
      type: "sounds-base",
      label: "Product System",
      title: "四个产品表面，组成一个声音系统。",
      summary: "四张真实屏幕对应 Home、Sounds、Player 与 Echo Garden 的产品关系。",
      badge: "03 / 04 · Evidence carrier",
      screens: [
        {
          id: "home",
          label: "Home",
          name: "Featured Mixes",
          note: "Featured Mixes 提供首个聆听入口。",
          src: "cases/soundsnomad/assets/home-featured.png",
          alt: "真实 SoundsNomad Home 与 Featured Mixes 产品截图",
        },
        {
          id: "sounds",
          label: "Sounds",
          name: "White Noise / Nature",
          note: "可组合的声音内容库。",
          src: "cases/soundsnomad/assets/sounds-catalog.png",
          alt: "真实 SoundsNomad Sounds 音效分类产品截图",
        },
        {
          id: "player",
          label: "Player",
          name: "Zen Garden",
          note: "将声音组合成个人场景。",
          src: "cases/soundsnomad/assets/player-zen-garden.png",
          alt: "真实 SoundsNomad Zen Garden 播放页面截图",
        },
        {
          id: "garden",
          label: "Garden",
          name: "Echo Garden",
          note: "收藏后的发现进入 Echo Garden。",
          src: "cases/soundsnomad/assets/profile-echo-garden.png",
          alt: "真实 SoundsNomad Profile 与 Echo Garden 产品截图",
        },
      ],
      systemRows: [
        ["01", "Library", "Sounds / White Noise / Nature"],
        ["02", "Experience", "Mix → Player → background listening"],
        ["03", "Context", "Field discovery → Echo Garden"],
      ],
      callout: "Field 将地图声源接入声音系统。",
      note: "四个界面共同呈现内容库、播放与场景收藏的产品关系。",
    },
    {
      type: "sounds-loop",
      label: "Workflow & Growth",
      title: "从产品定义到上线增长，形成一条协作链路。",
      summary: "产品定义、开发协作、内容生产与 ASO 分发，构成 SoundsNomad 的落地链路。",
      badge: "04 / 04 · Design → Dev → Content → Growth",
      steps: [
        ["01", "DEFINE", "产品设计与 PRD", "场景 → 主张 → 定义"],
        ["02", "BUILD", "设计与开发协作", "原型 → Simulator → Review"],
        ["03", "CREATE", "内容生产与内容库", "ElevenLabs + Suno → library"],
        ["04", "GROW", "ASO 与初期流量", "搜索 → 元数据 → 迭代"],
      ],
      aso: {
        title: "搜索意图 → 可见性",
        chain: ["搜索意图", "关键词清洗", "商店元数据", "上线观测", "迭代"],
        note: "初期流量来自社媒评论；商店字段、素材与排名反馈进入持续迭代。",
        pipeline: "3,282 raw terms → 689 clean terms → 50 shortlist",
      },
      flashcam: {
        title: "FlashCam / Selfie Glow Camera",
        note: "FlashCam 完成协作上线，ASO 截图呈现商店增长方法。",
        screens: [
          {
            id: "flashcam1",
            label: "ASO 01",
            src: "cases/soundsnomad/assets/flashcam-aso-1.png",
            alt: "FlashCam 第一张 ASO 证据截图",
          },
          {
            id: "flashcam2",
            label: "ASO 02",
            src: "cases/soundsnomad/assets/flashcam-aso-2.png",
            alt: "FlashCam 第二张 ASO 证据截图",
          },
        ],
      },
    },
  ],
});
